name: Tests
on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - name: Tests
      run: cargo test --workspace
